### ISSUE TITLE
Failed to activate the atom-medium package

### ISSUE THREAD

**Issue by pwent** [ericadamski/atom-medium#27]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-medium](https://github.com/ericadamski/atom-medium-upload) package 2.0.1

### Stack Trace

Failed to activate the atom-medium package

```
At this._acquireAccessToken is not a function

TypeError: this._acquireAccessToken is not a function
    at MediumClient.exchangeRefreshToken (/packages/atom-medium/node_modules/medium-sdk/lib/mediumClient.js:154:8)
    at tryCatcher (/packages/atom-medium/node_modules/rxjs/util/tryCatch.js:6:31)
    at BoundCallbackObservable._subscribe (/packages/atom-medium/node_modules/rxjs/observable/BoundCallbackObservable.js:204:64)
    at BoundCallbackObservable.Observable._trySubscribe (/packages/atom-medium/node_modules/rxjs/Observable.js:172:25)
    at BoundCallbackObservable.Observable.subscribe (/packages/atom-medium/node_modules/rxjs/Observable.js:160:93)
    at storeToken (/packages/atom-medium/lib/authenticate.js:107:12)
    at hasToken (/packages/atom-medium/lib/authenticate.js:63:9)
    at authenticate (/packages/atom-medium/lib/authenticate.js:116:12)
    at user (/packages/atom-medium/lib/client.js:15:12)
    at User.componentDidMount (/packages/atom-medium/lib/components/user.jsx:57:9)
    at Vh (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:216:198)
    at Zh (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:220:182)
    at /packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:250:268
    at Object.exports.unstable_runWithPriority (/packages/hydrogen-python/node_modules/scheduler/cjs/scheduler.production.min.js:18:163)
    at Fi (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:250:203)
    at Di (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:249:383)
    at Yh (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:248:144)
    at Xh (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:245:332)
    at qf (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:243:86)
    at Ji (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:253:14)
    at Ki (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:253:92)
    at Pi.render (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:261:109)
    at /packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:264:395
    at Hi (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:251:73)
    at Si (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:264:328)
    at render (/packages/hydrogen-python/node_modules/react-dom/cjs/react-dom.production.min.js:266:373)
    at /packages/atom-medium/lib/medium-upload-view.js:15:9)
    at Object.activate (/packages/atom-medium/lib/medium-upload.js:18:33)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3421604)
    at activationCommandSubscriptions.add.commandRegistry.onWillDispatch.o (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1879)
```

### Commands

```
     -0:03.7.0 medium-upload:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.17 
atom-material-ui 2.1.3 
atom-medium 2.0.1 
cacher 1.0.3 
export-html 3.1.0 
gruvbox-plus-syntax 1.3.1 
Hydrogen 2.10.3 
hydrogen-python 0.0.8 
language-latex 1.2.0 
latex 0.50.2 
markdown-themeable-pdf 1.2.1 
markdown-writer 2.11.6 
platformio-ide-terminal 2.9.1 
python-autopep8 0.1.3 
python-indent 1.2.3 
wordcount 3.1.0 
```

**Comment by ericadamski** [comment]
I will take a look into it 😄
